-- Time Off feature — run this once in the Supabase SQL Editor
-- (project hbxzbowkucpqlhxdomap) before using the new Time Off tab.
--
-- There is no migration tooling in this repo — every other table
-- (leave_records, estate_trips, duty_roster, audit_log, ...) was created the
-- same way, by hand, in the SQL Editor. This file is the source of truth for
-- the Time Off schema going forward.

create table time_off_records (
  id bigint generated by default as identity primary key,
  staff_name text not null,
  staff_email text not null,
  reason text not null,
  time_out timestamptz not null,
  time_in timestamptz,
  duration_minutes integer,
  entry_type text not null default 'live'
    check (entry_type in ('live','edited','backfilled','voided')),
  original_time_in timestamptz,   -- set once, on first correction; never overwritten again
  corrected_at timestamptz,
  created_at timestamptz not null default now()
);

create table time_off_reminders (
  id bigint generated by default as identity primary key,
  staff_name text not null,
  staff_email text not null,
  reason text not null,
  planned_date date not null,
  planned_time time not null,
  used boolean not null default false,
  created_at timestamptz not null default now()
);

alter table time_off_records enable row level security;
alter table time_off_reminders enable row level security;

-- Matches the current app-wide convention: every existing table is read and
-- written directly from the client via the hardcoded anon key, with only
-- UI-level ownership checks (see canManageLeave/canManageEstateTrip in
-- js/tab-leave.js and js/tab-estatetrip.js), not database-level ones.
-- Tightening this is tracked separately as a follow-up RLS hardening pass
-- across all tables, not something specific to Time Off.
create policy "anon full access" on time_off_records
  for all to anon using (true) with check (true);
create policy "anon full access" on time_off_reminders
  for all to anon using (true) with check (true);
